[docs]

title = "ReVanced Polling API"
description = """We do a little polling ඞ
## The official JSON API for ReVanced polls 🚀

### Important Information

* Rate Limiting - 60 requests per minute
* Cache - 5 minutes
* Token duration - 5 minutes

### Additional Notes

1. Breaking changes are to be expected
2. Client side caching is advised to avoid unnecessary requests
3. Abuse of the API will result in IP blocks

"""
version = "0.0.1"

[license]

name = "AGPL-3.0"
url = "https://www.gnu.org/licenses/agpl-3.0.en.html"

[logging]
level = "INFO"
json_logs = false

[cache]
expire = 300
database = 0

[slowapi]
limit = "60/minute"
database = 1

[tokens]
database = 2

[ballots]
database = 3

[auth]
access_token_expires = 300
